services:
  otel-python-app:
    image: obsfrancisco/otel-python-app:${APP_VERSION:-v0.33.0}
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    env_file: docker/env-files/otel-python-app.env
    links:
      - db-redis
      - db-mysql
      - observe-agent
    ports:
      - "8000:8000"

  db-redis:
    image: "redis:6.2-alpine"
    platform: linux/amd64
    ports:
      - "6379:6379"

  db-mysql:
    image: mysql:8.0.44
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: docker/env-files/mysql.env
    platform: linux/amd64
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  observe-agent:
    image: observeinc/observe-agent:2.8.1
    platform: linux/amd64
    env_file: docker/env-files/observe-agent.env
    ports: 
      - "4317"
      - "4318"
    volumes:
      - ./docker/etc/observe-agent/observe-agent.yaml:/etc/observe-agent/observe-agent.yaml