---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: generate-traffic
  namespace: otel-python
  annotations:
    resource.opentelemetry.io/service.name: "otel-python-app"
    resource.opentelemetry.io/service.namespace: "otel-python"
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: generate
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; wget http://otel-python-app:8080/users
          restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: flush-cache
  namespace: otel-python
  annotations:
    resource.opentelemetry.io/service.name: "otel-python-app"
    resource.opentelemetry.io/service.namespace: "otel-python"
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: flush-cache
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date; wget http://otel-python-app:8080/flush
          restartPolicy: OnFailure          