---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-python-app
  namespace: otel-python
spec:
  selector:
    matchLabels:
      app: otel-python-app
  template:
    metadata:
      labels:
        app: otel-python-app
      annotations:
        resource.opentelemetry.io/service.name: "otel-python-app"
        resource.opentelemetry.io/service.namespace: "otel-python"
        resource.opentelemetry.io/deployment.environment: "foobar"
        resource.opentelemetry.io/deployment.environment.name: "foobar"
    spec:
      containers:
        - name: otel-python-app
          image: obsfrancisco/otel-python-app:v0.24.0
          env:
          # - name: OTEL_RESOURCE_ATTRIBUTES
          #   value: deployment.environment.name=foobar
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: http://observe-agent-forwarder.observe.svc.cluster.local:4318
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          # - name: OTEL_SERVICE_NAME
          #   value: otel-python-app
          - name: OTEL_TRACES_EXPORTER
            value: otlp
          - name: OTEL_METRICS_EXPORTER
            value: otlp
          - name: OTEL_NODE_RESOURCE_DETECTORS
            value: env,host,os,serviceinstance
          - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
            value: "true"
          - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
            value: "delta"