apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - path: deployment.yaml

images:
  - name: obsfrancisco/otel-python-app
    newName: obsfrancisco/otel-python-app
    newTag: v0.31.0-arm

